export type Category = {
  categoryId: number;
  categoryName: string;
};

export const CATEGORYITEM: Record<number, string> = {
  1: 'FERRETERÍA',
  2: 'ACERO ESTRUCTURAL',
  3: 'ACERO DE REFUERZO',
  4: 'MATERIAL ELÉCTRICO',
  5: 'MATERIAL HIDRÁULICO',
  6: 'TUBERÍAS Y CONEXIONES HIDRÁULICAS',
  7: 'TUBERÍAS Y CONEXIONES SANITARIAS / PLUVIALES',
  8: 'GEOMEMBRANAS Y GEOTEXTILES',
  9: 'ADITIVOS PARA CONCRETO Y MORTERO',
  10: 'CONCRETO, MORTEROS Y PREFABRICADO',
  11: 'MADERAS Y PRODUCTOS DERIVADOS',
  12: 'IMPERMEABILIZANTES Y AISLAMIENTOS',
  13: 'PINTURAS Y RECUBRIMIENTOS',
  14: 'ACABADOS EN PISOS Y MUROS',
  15: 'HERRERÍA Y CANCELES METÁLICOS',
  16: 'VIDRIO Y CANCELERÍA DE ALUMINIO',
  17: 'CARPINTERÍA Y LAMINADOS',
  18: 'SEÑALAMIENTOS Y SEGURIDAD VIAL',
  19: 'EQUIPO DE SEGURIDAD Y EPP',
  20: 'HERRAMIENTA MENOR Y CONSUMIBLES',
  21: 'ARRENDAMIENTOS DE MAQUINARIA',
  22: 'ARRENDAMIENTOS DE OFICINAS Y SANITARIOS MÓVILES',
  23: 'EQUIPOS ESPECIALES Y SISTEMAS (CCTV, VOZ Y DATOS, CONTROL)',
  24: 'CLIMATIZACIÓN Y VENTILACIÓN (HVAC)',
  25: 'URBANIZACIÓN Y OBRA EXTERIOR',
  26: 'SERVICIOS ESPECIALIZADOS DE OBRA',
};

export type CategoryItem = (typeof CATEGORYITEM)[keyof typeof CATEGORYITEM];
